config/routes.rb
Rails.application.routes.draw do

  # resources :ideas
  # resources :reviews

  # resource :user
  resources :user_signed_in
  resources :users
  resource :session, only: [:new, :destroy, :create]

  # resources :likes, shallow: true,  only: [:create, :destroy]
  # get :liked, on: :collection



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'ideas#index'

  resources :ideas do
    resources :reviews, only: [:new, :create, :destroy]
    resources :likes, shallow: true, only: [:create, :destroy]
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

      user ||= User.new #guest user (not logged in)

    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
  
    alias_action :create, :read, :update, :delete, :to => :crud

    can :crud, Idea do |idea|
      user == idea.user
    end


    can :crud, Review do |review|
      user == review.user #|| review.idea.user
    end


    can :like, Idea do |idea|
      user.persisted? && idea.user != user
    end
  

    can :destroy, Like do |like|
      like.user == user
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/idea.rb
class Idea < ApplicationRecord
    belongs_to :user
    has_many :reviews, dependent: :destroy
    has_many :likes, dependent: :destroy
    has_many :likers, through: :likes, source: :user
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :idea

    validates(
        :idea_id,
        uniqueness: {
            scope: :user_id,
            message: "Idea has already been liked"
        }
    )

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :ideas, dependent: :destroy
    has_many :reviews, dependent: :destroy

    has_many :likes, dependent: :destroy
    has_many :liked_questions, through: :likes, source: :question

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= User.find_by_id session[:user_id]
  end


  helper_method :current_user
  
  def user_signed_in?
    current_user.present?
  end
  
  helper_method :user_signed_in?

    def authenticate_user!
        redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :find_idea, only: [:edit, :update, :show, :destroy]
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:index, :show ]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  # GET /ideas
  def index
    @ideas = Idea.order(created_at: :desc)
    
  end

  # GET /ideas/1
  def show
     @reviews = @idea.reviews.order(created_at: :desc)
    @review = Review.new
    @user = current_user
    @like = @idea.likes.find_by(user: current_user)
    # raise
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  def create
    @idea = Idea.new(idea_params)
    @idea.user = current_user
p "******** create *********" 

      if @idea.save
        redirect_to idea_path(@idea), notice: "Idea was successfully created." 
      else
        render :new, status: :unprocessable_entity 
      end
    end
  

  # PATCH/PUT /ideas/1
  def update
    respond_to do 
      if @idea.update(idea_params)
         redirect_to idea_url(@idea), notice: "Idea was successfully updated." 
      else
        render :edit, status: :unprocessable_entity 
      end
    end
  end

  # DELETE /ideas/1
  def destroy
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url, notice: "Idea was successfully destroyed." }
    end
  end

  private

    def find_idea
      @idea = Idea.find params[:id]
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_params
      params.require(:idea).permit(:title, :description)
    end

    def authenticate_user!
      redirect_to new_session_path, notice: "Please sign in" unless user_signed_in?
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :authenticate_user!, only: [:create, :destroy]

    def create
        @idea = Idea.find params[:idea_id]
        @like = Like.new(idea: @idea, user: current_user)

        if can?(:like, @idea)
            if @like.save
                flash.notice = "Idea liked"
            else
                flash.alert = @like.errors.full_messages.join(", ")
            end
        else
            flash.alert = "You cannot like this idea!"
        end
        redirect_to idea_path(@idea)
    end


    def destroy
       @like = current_user.likes.find params[:id]

       if !can?(:destroy, @like)
        flash[:warning] = "You cannot destroy a like you don't own!"
       elsif @like.destroy
        flash[:success] = "Idea Unliked"
       else
        flash[:warning] = "Couldn't Unlike the idea..."
       end
       redirect_to idea_path(@like.idea)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_review, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index, :show]
    before_action :authorize_user!, only: [:destroy]
  
    # idea /reviews
    def create
      @idea = Idea.find(params[:idea_id])
      @review = Review.new(review_params)
      @review.idea = @idea
      @review.user = current_user
  
      if @review.save
        flash[:success]="Review added"
      else
        @reviews = @idea.reviews.order(created_at: :desc)
        flash[:alert] = @review.errors.full_messages.join(", ")
  
      end
      redirect_to @idea
    end
  
    # DELETE /reviews/1
    def destroy
      @review = Review.find(params[:id])
      @idea = Idea.find(params[:idea_id])
      if can?(:crud, @review)
        @review.destroy
        redirect_to idea_path
        flash[:success] = 'Answer deleted'
      else
        redirect_to root_path, alert: 'Not Authorized to change answer!'
      end
    end
  
    private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
  
    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:description)
    end
  
    def authorize_user!
      redirect_to root_path, alert: 'Not Authorized!' unless can?(:crud, @review)
    end
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash[:alert] = "Wrong email or password"
      render :new
    end
  end

  def destroy
      session[:user_id] = nil
      redirect_to root_path
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    
    if @user.update(user_params)
      flash[:success] = "Username/password successfully updated"
      redirect_to edit_user_path @user
    else
      flash[:error] = "Something went wrong"
      render :edit
    end
  end  

  def change_password
    @user = User.find(params[:id])


  end
    

    private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :id,
      :password,
      :password_confirmation
    )
  end

  def password_params
    params.permit(:id, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ideas/_form.html.erb
<div class="container"> <%= form_with(model: idea) do |form| %>
  <% if idea.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
        <% idea.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit class: 'btn btn-outline-primary' %>
  </div>
<% end %>

</div>

app/views/ideas/_idea.html.erb
<div id="<%= dom_id idea %>">
  <p>
    <strong>Title:</strong>
    <%= idea.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= idea.description %>
  </p>

</div>

app/views/ideas/edit.html.erb
<h1>Editing idea</h1>

<%= render "form", idea: @idea %>

<br>

<div>
  <%= link_to "Show this idea", @idea %> |
  <%= link_to "Back to ideas", ideas_path %>
</div>

app/views/ideas/index.html.erb
<div class="container" >
<h1>Ideas</h1>

<div id="ideas">
  <div class="card">
      <% @ideas.each do |idea| %>
    <div class="card-body">
   <h3> <%= link_to idea.title, idea_path(idea.id) %></h3>
        
        <p><%= idea.description %></p>
        <p> <strong>Liked by:</strong> <%= idea.likes.count %> <p>
          
        <small> By <%= idea.user.first_name %> </small>

     </div>
     <hr>
      <% end %>
  </div>
</div>

</div>

app/views/ideas/new.html.erb
<div class="container"> <h1>Add Your Brilliant Idea! 🧠</h1>

<%= render "form", idea: @idea %>

<br>

</div>

app/views/ideas/show.html.erb
<div class ="container">

<h3>Idea by: <%= @idea.user.first_name  %> </h3>
<%= render @idea %>
 <small>Liked by: <%= @idea.likes.count %> users</small>


<div>
<% if can? :crud, @idea %>
  <%= link_to "Edit this idea", edit_idea_path(@idea), class: 'btn btn-outline-success' %> 
<% end %>
<% if current_user == @idea.user %>
  <%= button_to "Destroy this idea", @idea, method: :delete, class: 'btn btn-outline-danger' %>
<%end %>
<small>
  <% if @like.present? %>
      <%= button_to "👎 Unlike", like_path(@like), method: :delete, class: 'btn btn-outline-danger' %>
    <% else %>
      <%= button_to "👍 Like", idea_likes_path(@idea), method: :post, class: 'btn btn-outline-primary' %>
    <% end %>
</small>
</div>
<br>


<h3>Reviews</h3>
<br>
<div id="reviews">
    <div class="card">

      <% @reviews.each do |review| %>
      <div class="card-body">
        <%=review.description %>
        <br>
        <br>
        <small>Reviewed by <%= review.user.first_name %>, <%= time_ago_in_words(review.user.created_at)%> ago</small>
      <br>
        <% if current_user == review.user %>
          <div class="p-2"> <%= button_to "Delete", idea_review_path(@idea.id, review.id), method: :delete, class: 'btn btn-outline-danger btn-sm' %></div>
        <% end %>
     <hr>
      </div>
    <% end %>
    </div>
  

  
   
 

<%= form_with(model:[@idea, @review]) do |f| %>
  <div>
    <br>
    <%= f.text_area :description, cols: 50, rows: 3, placeholder: "Let us know what you think of this idea!" %> 
  </div>
  <%= f.submit "Submit", class:"btn btn-outline-primary" %>
  <br>
<% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaFactory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render 'welcome/header' %>
  <% flash.each do |type, message| %>
    <div class="alert alert-info" role=alert >
      <%= message %>
    </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_area :body %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>
<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit class:"btn btn-outline-primary" %>
<% end %>

app/views/welcome/_header.html.erb
<div class="container"> 
<nav class="navbar navbar-light navbar-expand bg-light justify-content-between ">
   <a class="navbar-brand" href="/"> 🧠 Idea Factory</a>

    <% if user_signed_in? %>
      <div> 👋 Hey, <%= current_user.first_name %>!</div>
     <% else %>
     <div> 👋 Welcome!</div>
     <% end %> 


   <div class="navbar-nav">

        <%= link_to "Home", root_path, class: "nav-item nav-link" %>
        
  <% if user_signed_in? %>
        <%= link_to "New idea", new_idea_path, class: "nav-item nav-link" %>
        <%= button_to "Logout", session_path, method: :delete,
            data: {confirm: "are you sure you want to log out?"}, class: 'btn btn-default nav-link'%>
  <% else %>
        <%= link_to "Login", new_session_path, class: "nav-item nav-link" %> 
        <%= link_to "Sign Up", new_user_path, class: "nav-item nav-link" %>
    <% end %>
  </div>
  
</nav>

</div>